apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-deployment
  labels:
    app: docker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
      - name: docker
        image: docker:rc-dind-rootless

