apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-storage 
provisioner: csi-driver.example-vendor.example
reclaimPolicy: Retain # default value is Delete
allowVolumeExpansion: true
mountOptions:
  - discard # this might enable UNMAP / TRIM at the block storage layer
volumeBindingMode: WaitForFirstConsumer
parameters:
  guaranteedReadWriteLatency: "true" # provider-specific
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pvc
  namespace: dynamic-storage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-storage
---
apiVersion: v1
kind: Pod
metadata:
  name: storage-pod 
  namespace: dynamic-storage
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: dynamic-pvc
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
      - containerPort: 80 
    volumeMounts:
      - mountPath: "/data"
        name: task-pv-storage