apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-storage
  namespace: dynamic-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fast-pv
  namespace: dynamic-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: fast-storage
  local:
    path: /mnt/data/fast
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - noda02
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pvc
  namespace: dynamic-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-storage
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: storage-pod
  namespace: dynamic-storage
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    volumeMounts:
    - name: storage-volume
      mountPath: /data
  volumes:
  - name: storage-volume
    persistentVolumeClaim:
      claimName: dynamic-pvc
