apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-map
  namespace: app-config
data:
  APP_ENV: "production"
  APP_DEBUG: "false"

---
apiVersion: v1
kind: Pod
metadata:
  name: config-pod
  namespace: app-config
spec:
  containers:
  - name: config-container
    image: busybox
    command: ["sh", "-c", "env | grep APP_"]
    env:
    - name: APP_ENV
      valueFrom:
        configMapKeyRef:
          name: app-config-map
          key: APP_ENV
    - name: APP_DEBUG
      valueFrom:
        configMapKeyRef:
          name: app-config-map
          key: APP_DEBUG