apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
  - name: config-pod-container
    image: busybox
    command: ['sh', '-c',"env | grep APP_"]
    env:
    - name: username
      valueFrom:
        configMapKeyRef:
          name: app-config-map
          key: username
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-map
data:
  username: "adibaknoor"
  