apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: config-pod
  name: config-pod
  namespace: app-config
spec:
  containers:
  - image: busybox
    name: config-pod
    command: ["sh", "-c", "env | grep APP_"]
    env:
      - name: APP_ENV
        valueFrom:
          configMapKeyRef:
            name: app-config-map
            key: APP_ENV
      - name: APP_DEBUG
        valueFrom:
          configMapKeyRef:
            name: app-config-map
            key: APP_DEBUG
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}