apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---

apiVersion: v1
kind: StatefulSets
metadata:
  name: postgres
  namespace: qq8
spec:
  volumes:
    - name: postgres-pv-storage
      persistentVolumeClaim:
        claimName: postgres-pv-claim
  containers:
    - name: postgres
      image: postgres:12.20-bullseye
      secretName: postgres-secret
      ports:
      - containerPort: 5432
      env:
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: POSTGRES_PASSWORD
      - name: POSTGRES_USERNAME
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: POSTGRES_USERNAME
      - name: POSTGRES_DB
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: POSTGRES_DB
      volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-pv-storage
---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
data:
  POSTGRES_PASSWORD: YWRpYjEyMw==
  POSTGRES_USER: YWRpYmFrbm9vcg==
  POSTGRES_DB: bXlzcWw=          
