apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: qq5
  labels:
    app: apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd 
        ports:
        - containerPort: 443 
---
apiVersion: v1
kind: Service
metadata:
  name: apache-svc
  namespace: qq5
spec:
  selector:
    app: apache 
  type: NodePort
  ports:
    - protocol: TCP
      port: 443
      targetPort: apache 
      nodePort: 30007