apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: apache
  name: apache
  namespace: qq5
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: apache
  type: LoadBalancer
status:
  loadBalancer: {}