apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
      - key: "key3"
        value: "value3"
        operator: "Equal"
        effect: "NoExecute"
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80