apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: qq6
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qq6-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: qq6
  local:
    path: /mnt/data/qq6
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node02
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qq6-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
  storageClassName: qq6
  volumeName: qq6-pv