apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: qq6          
provisioner: rancher.io/local-path
volumeBindingMode: Immediate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claim
spec:
  storageClassName: qq6
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi