apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: qq6
provisioner: kubernetes.io/example
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: qq6-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: qq6
  hostPath:
    path: /tmp

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qq6-pvc
spec:
  storageClassName: qq6
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi

