apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: qq6          
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: qq6
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/local

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: qq6
  resources:
    requests:
      storage: 7Gi
