apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: production
spec: {}
status: {}
---
apiVersion: apps/v1
kind: StorageClass
metadata:
  creationTimestamp: null
  name: fast
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-web-app
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: fast
  hostPath:
    path: /mnt/data/web-app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-web-app
  namespace: production
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: fast
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-app
  namespace: production
spec:
  serviceName: web-app
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
        volumeMounts:
        - name: web-app-storage
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: web-app-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: fast
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: web-app
  namespace: production
spec:
  ports:
  - port: 80
    targetPort: 80
  clusterIP: None
  selector:
    app: web-app




